
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hrms_development
  username: postgres
  password: omnipod

test:
  <<: *default
  database: hrms_test
  username: postgres
  password: omnipod


production:
  <<: *default
  database: hrms_production
  username: hrms
  password: <%= ENV['HRMS_DATABASE_PASSWORD'] %>
